# 启动一个服务
# + ca
# + orderer
# + peer 
# 
version: "3"

services:
  ca.org1.example.com:
    image: "hyperledger/fabric-ca:1.1.0"
    container_name: "org1_fabric_ca_server"
    ports:
      - 7053:7054 # 主机 : docker
    volumes:
      - /Users/zuvakin/workspace/src/go-advanced/docker-compose/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config/org1
    command: sh -c "fabric-ca-server start -b admin:adminpw -d"
    # command: fabric-ca-server start -b admin:adminpw -d

  ca.org2.example.com:
    image: "hyperledger/fabric-ca:1.1.0"
    container_name: "org2_fabric_ca_server"
    ports:
      - 7055:7054
    volumes:
      - /Users/zuvakin/workspace/src/go-advanced/docker-compose/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config/org2
    command: sh -c "fabric-ca-server start -b admin:adminpw -d"

  orderer.example.com:
    image: "hyperledger/fabric-orderer:1.1.0"
    container_name: "orderer"
    ports:
      - 7050:7050
    volumes:
      - /Users/zuvakin/workspace/src/go-advanced/docker-compose/solo/channel-artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /Users/zuvakin/workspace/src/go-advanced/docker-compose/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - /Users/zuvakin/workspace/src/go-advanced/docker-compose/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
    command: orderer

  # peer0.org1.example.com:
  #   image: "hyperledger/fabric-peer:1.1.0"
  #   container_name: "peer0_org1"
  #   ports:
  #     - 7051:7051  # grpc
  #     - 7053:7053  # event
  #   depends_on:
  #     - orderer.example.com
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
  #     - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
  #   command: peer node start

  # peer1.org1.example.com:
  #   image: "hyperledger/fabric-peer:1.1.0"
  #   container_name: "peer1_org1"
  #   ports:
  #     - 8051:7051
  #     - 8053:7053
  #   depends_on:
  #     - orderer.example.com
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
  #     - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
  #   command: peer node start

  # peer0.org2.example.com:
  #   image: "hyperledger/fabric-peer:1.1.0"
  #   container_name: "peer0_org2"
  #   ports:
  #     - 9051:7051
  #     - 9053:7053
  #   depends_on:
  #     - orderer.example.com
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
  #     - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
  #   command: peer node start

  # peer1.org2.example.com:
  #   image: "hyperledger/fabric-peer:1.1.0"
  #   container_name: "peer1_org2"
  #   ports:
  #     - 10051:7051
  #     - 10053:7053
  #   depends_on:
  #     - orderer.example.com
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp
  #     - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/tls
  #   command: peer node start