version: '3'

services:
  web:
    container_name: httpserver2
    image: myapp/httpserver:1.0.0
    ports:
      - "8020:8010"
    working_dir: /myapp
    volumes:
      - .:/myapp/
    command: httpserver